variables:  
  azureSubscription: 'Playground'  
  environment: develop  
  resourceGroup: 'playground'
  appName: 'standa-playground'
  slot: 'test'
  productionSlot: 'production'  
  stagingUrl: 'https://standa-playground-test.azurewebsites.net'
  url: 'https://standa-playground.azurewebsites.net'
  deploytoolsArtifact: 'DeployTools'
  webRequestAttempts: 5
  webRequestDelayInSeconds: 20

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Deploy/
    - deployment/
    - rootdevelop.yaml
pr:
- master
pool:
  vmImage: 'windows-latest'

stages:
- template: deployment/templates/build.yml
- template: deployment/templates/deploy.yml
  parameters:
    azureSubscription: $(azureSubscription)
    environment: $(environment)    
    resourceGroup: $(resourceGroup)
    appName: $(appName)
    slot: $(slot)
    productionSlot: $(productionSlot)
    stagingUrl: $(stagingUrl)
    url: $(url)
    deploytoolsArtifact: $(deploytoolsArtifact)
    webRequestAttempts: $(webRequestAttempts)
    webRequestDelayInSeconds: $(webRequestDelayInSeconds)
