parameters:
  solution: '../../**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  deploytoolsArtifact: 'DeployTools'
  slotInitializationTimeoutInMinutes: 20

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
      - script: echo ${{ parameters.slotInitializationTimeoutInMinutes }}
        displayName: Handle timeout

      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: ${{ parameters.solution }}

      - task: VSBuild@1
        inputs:
          solution: ${{ parameters.solution }}
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)"'
          platform: ${{ parameters.buildPlatform }}
          configuration: ${{ parameters.buildConfiguration }}

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: DeployPackage

      - publish: $(Build.SourcesDirectory)\deploytools.ps1
        artifact: ${{ parameters.deploytoolsArtifact }}

      # - task: PublishPipelineArtifact@1
      #   inputs:
      #     targetPath: $(Build.SourcesDirectory)\deploytools.ps1
      #     artifactName: ${{ parameters.deploytoolsArtifact }}