parameters:
  solution: '../../**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  utilsArtifact: 'DeployTools'  

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: ${{ parameters.solution }}

      - task: VSBuild@1
        inputs:
          solution: ${{ parameters.solution }}
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)"'
          platform: ${{ parameters.buildPlatform }}
          configuration: ${{ parameters.buildConfiguration }}

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: DeployPackage

      - publish: $(Build.SourcesDirectory)\utils.ps1
        artifact: ${{ parameters.utilsArtifact }}