parameters:
  environment: ''
  azureSubscription: ''
  resourceGroup: ''
  appName: ''
  slot: ''
  productionSlot: ''
  stagingUrl: ''
  url: ''
  deploytoolsArtifact: ''
  webRequestAttempts: 5
  webRequestDelayInSeconds: 15

stages:
- stage: Deploy
  jobs:
  - deployment: Deploy
    displayName: Deploy the application
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRMWebAppDeployment@4
            displayName: Azure App Service Deploy
            inputs:
              ConnectionType: AzureRM
              ConnectedServiceName: ${{ parameters.azureSubscription }}
              WebAppKind: webApp
              WebAppName: ${{ parameters.appName }}
              DeployToSlotOrASEFlag: true
              ResourceGroupName: ${{ parameters.resourceGroup }}
              SlotName: ${{ parameters.productionSlot }}              
              Package: $(Pipeline.Workspace)\DeployPackage\**\*.zip          
          
          - powershell: . $(Pipeline.Workspace)\${{ parameters.deploytoolsArtifact }}\deploytools.ps1 ; Retry({ SendWebRequest ${{ parameters.url }} }) ${{ parameters.webRequestAttempts }} ${{ parameters.webRequestDelayInSeconds }}
            displayName: Ping the production site
            timeoutInMinutes: 10

          - script: echo Slot initialization timed out
            condition: failed()
            displayName: Handle timeout