variables:  
  azureSubscription: 'Playground'  
  environment: develop  
  resourceGroup: 'playground'
  appName: 'standa-playground'
  slot: 'test'
  productionSlot: 'production'  
  stagingUrl: 'https://standa-playground-test.azurewebsites.net'
  url: 'https://standa-playground.azurewebsites.net'
  deploytoolsArtifact: 'DeployTools'
  webRequestAttempts: 5
  webRequestDelayInSeconds: 15
  location: 'West Europe'
  appServicePlan: 'ASP-playground-af4a'  

pr:
- develop
pool:
  vmImage: 'windows-latest'

stages:
- stage: Test
  jobs:
  - job: Test_Job_A
    steps:
    - task: AzurePowerShell@4
      inputs:
        azureSubscription: $(azureSubscription)
        azurePowerShellVersion: latestVersion
        scriptType: inlineScript
        inline: Get-AzContext -ListAvailable

    - task: AzurePowerShell@4
      inputs:
        azureSubscription: $(azureSubscription)
        azurePowerShellVersion: latestVersion
        scriptType: inlineScript
        inline: Get-AzWebApp -ResourceGroupName playground -Name standa-playground

    - task: AzurePowerShell@4
      displayName: Clone Web Application
      inputs:
        azureSubscription: $(azureSubscription)
        azurePowerShellVersion: latestVersion
        scriptType: filePath
        scriptPath: $(Build.SourcesDirectory)\cloneWebApp.ps1
        scriptArguments:
          -location "$(location)" `
          -appServicePlan $(appServicePlan) `
          -resourceGroup $(resourceGroup) `
          -sourceAppName $(appName) `
          -destinationAppName "pipeline-cloned-app"

    # - powershell: Get-AzContext -ListAvailable
    #   displayName: Get available contexts
    # - powershell: Get-AzWebApp -ResourceGroupName playground -Name standa-playground
    #   displayName: Get web app

# - template: templates/build.yaml
# - template: templates/deploy.yaml
#   parameters:
#     azureSubscription: $(azureSubscription)
#     environment: $(environment)    
#     resourceGroup: $(resourceGroup)
#     appName: $(appName)
#     slot: $(slot)
#     productionSlot: $(productionSlot)
#     stagingUrl: $(stagingUrl)
#     url: $(url)
#     deploytoolsArtifact: $(deploytoolsArtifact)
#     webRequestAttempts: $(webRequestAttempts)
#     webRequestDelayInSeconds: $(webRequestDelayInSeconds)
