variables:  
  azureSubscription: 'Playground'  
  environment: develop  
  resourceGroup: 'playground'
  appName: 'standa-playground'
  destinationAppName: 'pipeline-cloned-app'
  slot: 'test'
  productionSlot: 'production'
  stagingUrl: 'https://standa-playground-test.azurewebsites.net'
  url: 'https://standa-playground.azurewebsites.net'
  deploytoolsArtifact: 'DeployTools'
  webRequestAttempts: 5
  webRequestDelayInSeconds: 15
  location: 'West Europe'
  appServicePlan: 'ASP-playground-af4a'
  sqlServerResourceGroup: 'cloud-shell-storage-westeurope'
  sqlServerName: 'prenv'
  sqlServerUserName: 'MEWS-E87C21D3-9A9F-4369-B039-4738B3CBE65F'
  sqlServerPassword: '6E3DE82B-DF77-4C1B-8AF3-E104E7D5FBBC'
  sqlDatabaseName: 'pipeline-created-sqldb'
  sqlDatabaseEdition: 'Standard'
  connectionStringName: 'mews-develop-sql-weu/mews-develop-db'
  

trigger: none
pr:
- master
pool:
  vmImage: 'windows-latest'

stages:
- stage: Infrastructure_setup
  displayName: Set up the environment
  jobs:
  - job: Create_infrastructure
    displayName: Create the infrastructure
    steps:
    - task: AzurePowerShell@4
      displayName: Create the App Service
      inputs:
        azureSubscription: $(azureSubscription)
        azurePowerShellVersion: latestVersion
        scriptType: filePath
        scriptPath: $(Build.SourcesDirectory)\cloneWebApp.ps1
        scriptArguments:
          -location "$(location)" `
          -appServicePlan $(appServicePlan) `
          -resourceGroup $(resourceGroup) `
          -sourceAppName $(appName) `
          -destinationAppName $(destinationAppName)-$(System.PullRequest.PullRequestNumber)

    - task: AzurePowerShell@4
      displayName: Create SQL Database
      inputs:
        azureSubscription: $(azureSubscription)
        azurePowerShellVersion: latestVersion
        scriptType: filePath
        scriptPath: $(Build.SourcesDirectory)\createSqlDatabase.ps1
        scriptArguments:
          -location "$(location)" `
          -resourceGroup $(sqlServerResourceGroup) `
          -serverName $(sqlServerName) `
          -serverUserName $(sqlServerUserName) `
          -serverUserPassword $(sqlServerPassword) `
          -edition $(sqlDatabaseEdition) `
          -databaseName $(sqlDatabaseName)-$(System.PullRequest.PullRequestNumber)

    - task: AzurePowerShell@4
      displayName: Update the web app settings
      inputs:
        azureSubscription: $(azureSubscription)
        azurePowerShellVersion: latestVersion
        scriptType: filePath
        scriptPath: $(Build.SourcesDirectory)\updateWebAppSettings.ps1
        scriptArguments:
          -resourceGroup $(resourceGroup) `
          -appName $(destinationAppName)-$(System.PullRequest.PullRequestNumber) `
          -connectionStringName $(connectionStringName) `
          -sqlServerName $(sqlServerName) `
          -databaseName $(sqlDatabaseName)-$(System.PullRequest.PullRequestNumber) `
          -serverUserName $(sqlServerUserName) `
          -serverUserPassword $(sqlServerPassword)

- template: ./templates/build.yml
  parameters:
    utilsPath: $(utilsPath)
    utilsArtifact: $(utilsArtifact)

- template: ./templates/deploy-without-preview.yml
  parameters:
    azureSubscription: $(azureSubscription)
    environment: $(environment)
    resourceGroup: $(resourceGroup)
    appName: $(destinationAppName)-$(System.PullRequest.PullRequestNumber)
    productionSlot: $(productionSlot)
    url: 'https://$(destinationAppName)-$(System.PullRequest.PullRequestNumber).azurewebsites.net'
    deploytoolsArtifact: $(deploytoolsArtifact)
    webRequestAttempts: $(webRequestAttempts)
    webRequestDelayInSeconds: $(webRequestDelayInSeconds)