variables:  
  azureSubscription: 'Playground'  
  environment: develop  
  resourceGroup: 'playground'
  appName: 'standa-playground'
  slot: 'test'
  productionSlot: 'production'  
  stagingUrl: 'https://standa-playground-test.azurewebsites.net'
  url: 'https://standa-playground.azurewebsites.net'
  deploytoolsArtifact: 'DeployTools'
  webRequestAttempts: 5
  webRequestDelayInSeconds: 15

# Comment

trigger:  
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - notes.md
pr:
- master
pool:
  vmImage: 'windows-latest'

stages:
- template: templates/build.yaml
- template: templates/deploy.yaml
  parameters:
    azureSubscription: $(azureSubscription)
    environment: $(environment)    
    resourceGroup: $(resourceGroup)
    appName: $(appName)
    slot: $(slot)
    productionSlot: $(productionSlot)
    stagingUrl: $(stagingUrl)
    url: $(url)
    deploytoolsArtifact: $(deploytoolsArtifact)
    webRequestAttempts: $(webRequestAttempts)
    webRequestDelayInSeconds: $(webRequestDelayInSeconds)
